### ISSUE TITLE
不是  issue 的 issue

### ISSUE THREAD

**Issue by liudongmiao** [RikkaW/Shizuku#1]
以下假定你看过 brevent-server 的部分源码。
因为从源码结构，以及核心的实现上，与 brevent-server 有着很大的类似。
如果并没有读过，完全是你的独立想法，也可以简单参考下。

比如说，Server 为什么要 extends Handler，特别是你什么也没做的情况下。
没有 await 的 CountDownLatch 有什么意义呢？

就传递数据来说，parcel 比其它的方式，如 json 等，好在哪？
如果根本不使用 Intent（隐含 Bundle）的话，还有必要使用 Parcelable 么？

作为库而言，直接 catch Exception，没有任何日志，是否恰当？

**Comment by elhizazi1** [comment]
اختبار التعليقات

**Comment by 91Alg** [comment]
神

**Comment by qwmm1234** [comment]
Very good

**Comment by tomekkowal197** [comment]
There are better shizuku alternatives like shizuku + or shevery

**Comment by SirAnfer1981** [comment]
ojo no función cuando se activa la opción de aceleración de red, cuando se conecta a dos redes WiFi para mejorar la conexión, en un poco x8 pro max, deberían tratar de solucionar para poder utilizar como. esta configuracion
