### ISSUE TITLE
Rikka，可不可以使用网络adb调试开启shizuku服务呢

### ISSUE THREAD

**Issue by maxiye** [RikkaW/Shizuku#2]
这样就可以不输入命令了

**Comment by RikkaW** [comment]
这样就要引入别的东西，而且应该只有各种自定义 ROM 有打开网络 adb 的功能，这样的 ROM 通常也没有非 root 使用的需求..
所以就.. 不加了（

**Comment by maxiye** [comment]
坏耶（

**Comment by liudongmiao** [comment]
引入别的东西倒也未必吧...

Brevent 的简化版 adb 协议（只执行命令），也就不到 300 行，更不用指定什么端口。

核心代码，也不过就 40 行的样子。
