### ISSUE TITLE
Start Zhizuku Server without adb on no root devices

### ISSUE THREAD

**Issue by rexii2300** [RikkaW/Shizuku#8]
Brevent app here has experimental mode where the server can be started without adb. 

https://github.com/brevent/Brevent

Is it possible to start Shizuku Server using a similar technique?

**Comment by liudongmiao** [comment]
Did you mean network adb?

https://github.com/brevent/Brevent/blob/master/brevent/src/main/java/me/piebridge/brevent/ui/SimpleAdb.java

It's simple version of network adb, and I think it's easy to implement it use third-party library.

Brevent cannot be started without adb on unrooted devices.

**Comment by liudongmiao** [comment]
it seems @rexii2300 has misunderstanding on Brevent: https://github.com/brevent/Brevent/issues/3

just close it.

**Comment by rexii2300** [comment]
@liudongmiao I opened this issue before we clarified the server and root requirements. I now understand Brevent can't be started without adb on unrooted devices. I'll close the comment now

**Comment by shankarnane29-sys** [comment]
Shizuku stops when screen is locked on OneUI 8
